### ISSUE TITLE
Potential source of bugs in setColor(std::ostream& os, T const value)

### ISSUE THREAD

**Issue by HemilTheRebel** [agauniyal/rang#109]
There is this piece of code which can lead to surprising behaviour
```c++
template <typename T>
inline enableStd<T> setColor(std::ostream &os, T const value)
{
        return os << "\033[" << static_cast<int>(value) << "m";
}
```
I understand that:

1. They are a part of the rang_implementation namespace which most people won't touch (i hope no one does :P)
2. It will only compile on non-windows operating systems.

But it can be a potential cause of bugs. Because (as I see) it is used with template parameter and we don't have concepts yet. We might want to make sure it is something that rang supports. We could use macros to enable the checks in debug build and disable them in release build so that performance is not impacted. 

P.S: Found this while watching Jason Turner's CppCon 2018 talk, "Applied best practices". Around after the 37th minute.

**Comment by Lecrapouille** [comment]
@HemilTheRebel I did not understand well the meaning of "we don't have concepts yet" so I hope to answer you correctly concerning "We might want to make sure it is something that rang supports. We could use macros to enable the checks"

In the code there is already you check with:
```
    template <typename T>
    using enableStd = typename std::enable_if<
      std::is_same<T, rang::style>::value || std::is_same<T, rang::fg>::value
        || std::is_same<T, rang::bg>::value || std::is_same<T, rang::fgB>::value
        || std::is_same<T, rang::bgB>::value, std::ostream &>::type;
```
* It acts like a macro (so checked at compiled time). The `using` is equivalent to `#define` therefore `enableStd` is an alias of the boilerplate template code because it will be used several times in the code.  I'm not a huge fan of C++ template syntax but `enable_if` allows the function setColor to be templated if and only if T is of one of the following type rang::style or rang::bg or rang::bgB or rang::fg or rang::fgB. 
* because rang::style ... are typed of `class enum` they are strongly type and therefore cannot be implicitly casted from/to an integer. Finally you cannot pass another kind of type to this function.

So everything is alright in my opinion. Of course you try forcing casting a wrong integer value into one of this type (for example `rang::fgB foo = static_cast<rang::fgB>(-1)`), this will force setColor to have an wrong value.

**Comment by HemilTheRebel** [comment]
My bad. Skipped the enablestd
