### ISSUE TITLE
Exposing <windows.h> on Windows

### ISSUE THREAD

**Issue by AxelStrem** [agauniyal/rang#34]
Opening this to discuss possible solutions.  
As it is, rang.hpp requires several declarations from `<windows.h>`:  
- `HANDLE`
- `STD_OUTPUT_HANDLE`
- `WORD, DWORD`
- `GetStdHandle(DWORD)`
- `SetConsoleTextAttribute(HANDLE, WORD)`

Exposing `<windows.h>` is actually quite bad not only because of autocomplete clogging, but it also defines several nasty macros, e.g. `min` and `max`, which obviously conflict with `std::min` and `std::max`.  
On other hand `<windows.h>` depends on some user-defined macros and of course has `#include` guards, so including it before the place user intends to include it can lead to unexpected behavior.

So far the best solution I came up with is just to declare all the required stuff by hand (in case `<windows.h>` is not already included by user). As ugly as it is, I can think of no other options.

**Comment by agauniyal** [comment]
I see no reason why they would choose so generic method names - `min` & `max` 😪 , although we do have a macro #define NOMINMAX for that, but that might break other things that depend on `windows.h`. How about asking user for including `windows.h` before including `rang.hpp` in his code? This way the user himself would be in charge of dealing with those stuff however he likes to.

Autocomplete clogging isn't an issue since either way windows specific functions are going to end up in autocompletion menu, I was talking about the methods present in `rang.hpp` source which weren't inside anonymous namespace, they would be unnecessarily shown in autocomplete.

>So far the best solution I came up with is just to declare all the required stuff by hand (in case <windows.h> is not already included by user). As ugly as it is, I can think of no other options.
I don't understand this part, how are we going to declare them?

**Comment by AxelStrem** [comment]
`windows.h` is so sad it's actually kinda funny :D 
OK, since you've been talking about `rang.hpp` implementation methods, I'll just wrap them up now and we can leave this `windows.h` problem for further discussion.
Personally I think asking user to include it is a good option, this header is so cancerous it's better be as explicit as it gets.
We can add some nice compiler error message macro to clarify this requirement. The only drawback is that `rang.hpp` won't work out of the box on windows then.
Just leaving it as it is may not be so bad too after all.

**Comment by agauniyal** [comment]
@AxelStrem I'm in favour of leaving it as it is, unless there's some strong reason to not do so. If user is going to use this lib, he'll have to include `<windows.h>` anyhow. Once I release v2.0 in a few days, which will cover all windows versions, I'll post it to other reviewing sites to get a feedback about current implementations and see if someone points out to separate out it again.
