### ISSUE TITLE
←[0m←[42m←[37mIf in the console ouptut instead of showing bg and fg colors

### ISSUE THREAD

**Issue by dileepsankhla** [agauniyal/rang#4]
I tried your windows version of header file `rang.hpp `on windows 8.1 using visual C++ compiler (IDE: Visual Studio 12.0) and this was the output for the source code `visualTest.cpp`:

`←[0m←[42m←[37mIf you're seeing green bg, then rang works!←[0m`

I will be glad to contribute in this project for developing this header only library for windows version.

**Comment by agauniyal** [comment]
Currently rang supports only up to date Windows 10 machines since the newer cmd supports colorful output similar to Linux machines. You need to look at [SetConsoleTextAttribute](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686047%28v=vs.85%29.aspx) function and determine windows version < 10 at compile time, and provide appropriate calls using SetConsoleTextAttribute for them. So there are two steps for an optimal solution - 

1. Detect windows versions less than 10
2. And then substitute current coloring methods with SetConsoleTextAttribute for them.

**Comment by agauniyal** [comment]
Dulplicate of #2
