### ISSUE TITLE
Respect ANSICON environment variable on Windows

### ISSUE THREAD

**Issue by sbellon** [agauniyal/rang#72]
If environment variable ANSICON is set on Windows, the console is capable of ANSI sequences, so preferably use them.

What about this patch?

>  --- a/include/rang.hpp
>  +++ b/include/rang.hpp
>  @@ -205,6 +205,7 @@ namespace rang_implementation {
>          inline HANDLE getVersionDependentHandle()
>          {
>                  if (IsWindowsVersionOrGreater(10, 0, 0)) return nullptr;
>  \+               if (getenv("ANSICON")) return nullptr;
>                  return GetStdHandle(STD_OUTPUT_HANDLE);
>          }
>   

Sorry for the formatting, it seems markup is mocking up ...

**Comment by kingseva** [comment]
Well, ANSICON is a DLL extension for native Windows console (cmd.exe). https://www.photogabble.co.uk/blog/tools-and-resources/ansi-command-line-colors-under-windows/
From windows 10 microsoft added support of ansi colour sequences, and Rang internally can use it. 

Don't forget that Rang is crossplatform lightweight interface for colour terminal. It's goal to provide same interface on any backend like ANSI escape sequencies or native Console API functions. If you want to use ANSI escape sequencies directly to stdout/stderr you don't need Rang. 

Take a look of comparision of rang and ansicon. Tested on WinXP x86. On left is rang test application builded from next-release branch, that use console API. On right is rang test application runned on ansicon but forced to use ansi sequences.

![rang-ansicon](https://user-images.githubusercontent.com/9908175/34553368-ae9d0034-f159-11e7-8591-7bf6be04a6f4.png)

ANSICON don't adds any new styles to cmd.exe like italic or blink. So it's unnecessary to use it by rang.

**Comment by sbellon** [comment]
Yes, but with that one-line patch colors are more vivid when run from within ANSICON than without that patch.

**Comment by kingseva** [comment]
I'm agree that rang can emulate support of bold, reversed... etc styles same as ANSICON terminal. Otherwise i don't see any difference on screenshots above. Can you drag and drop comparision screenshots of your app to see that difference?

**Comment by sbellon** [comment]
<img width="497" alt="2018-01-04_09h05_45" src="https://user-images.githubusercontent.com/1427724/34554744-ab5c2fce-f12e-11e7-8641-1a70ba035039.png">

On the left is the output of yellow and red with my patch inside an ANSICON terminal, on the right side without my patch. This is on Windows 10 Fall Creators Update.

**Comment by kingseva** [comment]
Is it next-release branch?

**Comment by sbellon** [comment]
No, this is master. Is this deprecated? Should I use next-release branch?

**Comment by kingseva** [comment]
I'm think yes because master branch still have an old bug #66. Master branch should be updated later when @agauniyal makes a decision

**Comment by sbellon** [comment]
But even with next-release branch I get more vivid colors when doing this in setWinTermAnsiColors():

`        return true;
    } else if (getenv("ANSICON")) {
        return true;
    } else {
        return false;`

**Comment by kingseva** [comment]
Ok, you use style::bold of warning/error text? If it is, rang on current version don't emulate bold text as you can see on my screenshot above. Better to emulate it inside setWinAttribute function instead of dependency from ANSICON. Try to add this code to setWinAttribute: 
```c++
        if (style == rang::style::bold) {
            state |= 0x8;
        }
```

I'm think it should be added on next release as other styles like reversed.

**Comment by sbellon** [comment]
Ok, that works. Thank you.

**Comment by kingseva** [comment]
**Update.** Don't forget to use 0xFFF8 in setWinAttribute(rang::fg... ) because now it's should preserve flag of bright text after bold operation. See patch above.

**Comment by sbellon** [comment]
Hm, those bit/flag operations seem indeed a bit fragile to me. Don't the Windows headers define macros that could be used here instead?

**Comment by kingseva** [comment]
That's original code from rang repository. Maybe code don't use any macro names due to portability. But of course it's better to use macro names instead of magic numbers. Macro names can be used from wincon.h https://docs.microsoft.com/en-us/windows/console/console-screen-buffers 

It's possibel to rewrite that code after all tasks, but it's required to check as much as possible compilers to support that macro definitions. You can write pull request or patch if you want.

**Comment by sbellon** [comment]
BTW, shouldn't that be `state |= 0x88` and in setWinAttribute(rang:fg...) then `0xFFF8` and additionally in setWinAttribute(rang:bg...) then `0xFF8F` as well because "intensity" can also apply to background?

**Comment by kingseva** [comment]
No, it shouldn't. Note that all this enum codes is used inside ASCII sequences. As we use this trick, for better compability all code that use winapi should work like ASCII sequences backend as much as possible. From ANSICON sequences [manual](https://github.com/adoxa/ansicon/blob/master/sequences.txt#L17-L19) we can see that bold is emulated  strictly for foreground and underline/blink style is used only for background.

```text
		 1	bold (foreground is intense)
		 4	underline (background is intense)
		 5	blink (background is intense)
```

You can implement this behaviour in setWinAttribute functions. It would be good pull request :smiley: 

But i'm think the reason it's still not implemented is that users won't use style options due to different behaviour on windows/linux terminals. Linux terminals supports true bold, blink etc, while even Win10 is not. So, for the better portability reason styles used very rarely, only background/foreground with or without intense.

**Comment by agauniyal** [comment]
I've actually touched very little part of windows code(just slight maintenance) and have relied on community support for it. I was waiting for #71 to get merged before merging `next-release` into `master` and make a new release of rang since that removes one pain point of manually including versionhelpers.h file on older targets. I'm open to changes regarding usage of macros as well as the changes discussed above and I don't remember why they aren't being used in first place 🤔. Also @kingseva I would like to make you collaborator of this repo since you're well versed with windows code(more than I am 😄) which will allow you to make changes/accept PRs faster if you are okay with it 😁.

**Comment by agauniyal** [comment]
@sbellon can you check the latest `next-release` branch commit, @kingseva submitted a PR related to above discussion and if you're happy we'd close this issue 😄

**Comment by sbellon** [comment]
Yes, works fine. Thanks a lot! :-)
