### ISSUE TITLE
Potential UB in isMsysPty function

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/rang#82]
At line - https://github.com/agauniyal/rang/blob/master/include/rang.hpp#L195

Relevant comments from slack chat -
> djarek
> don't know winapi at all, but that looks like straight UB

> kaboissonneault
> I don't know if that's UB. `GetFileInformationByHandleEx` will create a proper object in that location.
> But to be safe, I'd do the reinterpret_cast _after_ calling GetFileInformationByHandleEx with the buffer. Though now that I think about it, isn't `static_cast` sufficient ?

> glenfe
> @kaboissonneault No. What alignment is buffer guaranteed to have?

> kaboissonneault
> Okay, then `buffer` should be properly aligned

> glenfe
> If it's not properly aligned, it's UB.
> The only guarantees you have for `char buffer[100];` are that is aligned suitably for `char`s. If you want higher alignment value guarantees (because the `FILE_NAME_INFO` type has higher alignment requirements, you need to use `alignas` (or `std::aligned_storage`).

> std::malloc(), ::operator new(std::size_t), ::operator new(std::size_t, const std::no_throw_t&) can be used to obtain storage that is suitably aligned for all fundamental types. i.e. Up to alignof(std::max_align_t).
> char c[N]; doesn't have those guarantees

**Comment by agauniyal** [comment]
There are few other warnings - http://rextester.com/TGIJP95971, mostly harmless I think. One that stood out was -
```cpp
warning C4191: 'reinterpret_cast': unsafe conversion from 'FARPROC' to 'BOOL (__cdecl *)(HANDLE,FILE_INFO_BY_HANDLE_CLASS,LPVOID,DWORD)'
        Calling this function through the result pointer may cause your program to fail
```
pointing to -
```cpp
const auto ptrGetFileInformationByHandleEx
          = reinterpret_cast<decltype(&GetFileInformationByHandleEx)>(
            GetProcAddress(GetModuleHandle(TEXT("kernel32.dll")),
                           "GetFileInformationByHandleEx"));
```

**Comment by kingseva** [comment]
Ok. Take look into struct FILE_NAME_INFO defined in WinBase.h

``` c++
        typedef struct _FILE_NAME_INFO {
            DWORD FileNameLength;
            WCHAR FileName[1];
        } FILE_NAME_INFO, *PFILE_NAME_INFO;
```
Data alignment of this struct is 4 on x86/x86_64, and sizeof is 8 on both architectures.
The definition of **nameinfo** comes from this code:
``` c++
        constexpr const DWORD size
          = sizeof(FILE_NAME_INFO) + sizeof(WCHAR) * (MAX_PATH + 1);
        char buffer[size];
        FILE_NAME_INFO *nameinfo
          = reinterpret_cast<FILE_NAME_INFO *>(&buffer[0]);
```
1. We use sizeof(FILE_NAME_INFO) but not sizeof(DWORD ) + sizeof(WCHAR). This means that we assume that all padding inside struct is used correctly for determining it's size. So, we take into account the data alignment within the structure by this code. But even this not required here. GetFileInformationByHandleEx writes text right after FileNameLength. So, I think we can use sizeof(DWORD) + sizeof(WCHAR) * (MAX_PATH + 1). All we need is to reserve memory for calling this function.

2. We don't need  **adress** alignment of buffer because compiler will do this for us. All modern CPU works with aligned data. As I know default alignment of stack variables can not become lower than  sizeof(void*). Manual adress alignment is required for example in SIMD processing for alignment more than sizeof(void*). CPU generate exception trying to load data from unaligned memory into SIMD  register. As i know VS 2010 is not support alignas/aligof. Only modern versions of Visual Studio can support it. And of course MSDN, nothing says about the requirement to align the output address. https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa364953(v=vs.85).aspx

@glenfe please correct me if I'm wrong.

3. @agauniyal C4191 means that compiler doesn't know which function should be returned from GetProcAdress in runtime. This warning will disabled by default by MS. The only way is avoid this is explicitly disable in code:
``` c++
#if defined(_MSC_VER)
#pragma warning(disable:4191)
#endif
```
Any other Extra warnings for singed/unsigned assignment can be fixed, it's not fatal.

**Comment by djarek** [comment]
The compiler is not required to over-align objects with automatic storage duration. Here's a counterexample to your theory of "all modern CPUs [...]": https://wandbox.org/permlink/93g0rJHgCCvkoJUd

If you're making assumptions about the target implementation of C++, you should verify them. Preferably at compile time, but if not possible, do it at run time. And if doing runtime checks triggers disgust in you, then don't make such assumptions unnecessarily and write portable code (i.e. code that targets the abstract machine described by the ISO C++ standard).

**Comment by kingseva** [comment]
@djarek Thanks for your example. It confirms that code will wok even buffer is unaligned. It's a joke :smile:. Maybe i'm lucky and not seen any problems before during testing because it's always been created as aligned... I don't know.  

LOL, Its really interesting how to use GetFileInformationByHandleEx wihout undefined behaviour :smiley: Please ask Microsoft how to do this :rofl: 

Ok, consider we want to add alignment to buffer.

Solution number 1. Does this code should be correct without any undefined behaviour? 

``` c++
    constexpr const DWORD size
            = sizeof(FILE_NAME_INFO) + sizeof(WCHAR) * (MAX_PATH + 1);

    alignas(FILE_NAME_INFO) char buffer[size];
    FILE_NAME_INFO *nameinfo = new(&buffer[0]) FILE_NAME_INFO;
```
Note that I'm replace reinterpret_cast with placement new. It's should be do the same thing but looks better without cast.

Solution number 2. Using heap instead of automatic variables:
```c++
    constexpr const size_t alignment = alignof(FILE_NAME_INFO);
    constexpr const size_t size = sizeof(FILE_NAME_INFO) + sizeof(WCHAR) * (MAX_PATH + 1);

    auto buffer = std::unique_ptr<BYTE,decltype(&_aligned_free)>(
        static_cast<BYTE*>(_aligned_malloc(size,alignment)),&_aligned_free );

    FILE_NAME_INFO *nameinfo = new(buffer.get()) FILE_NAME_INFO;

```
MSVC is not support alignas/alignoff below MSVC 2015. Can we agreed with this restriction? :thinking: 
Well, If not, we know that alignment of struct is equal maximum size of it's member. 
``` c++
    constexpr const size_t alignment = 
        sizeof(DWORD) > sizeof(WCHAR) ? sizeof(DWORD) : sizeof(WCHAR);
```
It's worse but should work if we assume that declaration API of GetFileInformationByHandleEx and  FILE_NAME_INFO is never changed by MS for backward compatibility with most of software.

What else we can do with this code to call GetFileInformationByHandleEx?

**Comment by glenfe** [comment]
> @glenfe please correct me if I'm wrong.

You are wrong: It is UB. Please read [[basic.align]](http://www.eel.is/c++draft/basic.align). Those are the only guarantees you have. 

You've determined that `alignof(T)` on one C++ implementation is N. You know that `alignof(char)` on all implementations are 1. If you're writing code that assumes `char buffer[S];` is always at least `alignof(T)` aligned then you have UB and you might be targeting behavior that a specific C++ implementation is giving you.  But you might be surprised to find that even that particular C++ implementation doesn't guarantee you that behavior in all cases.

> MSVC is not support alignas/alignoff below MSVC 2015.

You can use `boost::type_with_alignment` or `boost::aligned_storage`. It should support MSVC 2005, 2008, 2010, 2012, 2013, 2015 and 2017, for fundamental alignment values (and some extended alignment values).
