### ISSUE TITLE
Use printf instead of cout

### ISSUE THREAD

**Issue by illera88** [agauniyal/rang#93]
Hi,
i would like to know how can I use your library with `printf`.

Something like: 

```
printf("%sHi, there!%s", rang::bg::magenta, rang::bg::reset);
```
This does not work since using `%s` expects a `char*` and not a `enum` as `rang::bg::magenta` is.

Thank you

**Comment by agauniyal** [comment]
@illera88 currently, this library is based heavily on streams so this is not possible for now. The code is under The Unlicense and I encourage people to take bits of it and reuse it for themselves if you want this functionality right now.

I am willing to accept PRs for `rang::to_string(rang::enums)` method if someone wants a take on it otherwise I'll add that method in the upcoming version. I'm finding littel time to work on OSS for some time :sweat_smile:

**Comment by agauniyal** [comment]
I don't know a way to make rang work with printf and still support older Windows versions( < 10), not thinking of leaving those versions anytime soon so closing this issue. If need arises, I can think of making some other API which works with printf but that would be a hack instead of proper code...
